//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaniWaniBlack.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KaniWaniBlackEntities : DbContext
    {
        public KaniWaniBlackEntities()
            : base("name=KaniWaniBlackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserVocab> UserVocabs { get; set; }
        public virtual DbSet<WaniKaniVocab> WaniKaniVocabs { get; set; }
    }
}
