//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaniWaniBlack.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVocab
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int WKVocabID { get; set; }
        public bool IsBurned { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string UserSynonyms { get; set; }
    
        public virtual User User { get; set; }
        public virtual WaniKaniVocab WaniKaniVocab { get; set; }
    }
}
