//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaniWaniBlack.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaniKaniVocab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WaniKaniVocab()
        {
            this.UserVocabs = new HashSet<UserVocab>();
        }
    
        public int ID { get; set; }
        public int Level { get; set; }
        public string Character { get; set; }
        public string Kana { get; set; }
        public string Meaning { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVocab> UserVocabs { get; set; }
    }
}
